spring:
  application:
    name: spring-elastic
  data:
    elasticsearch:
      uris: ${ES_URIS:https://localhost:9200}
      username: ${ES_USERNAME:elastic}
      password: ${ES_PASSWORD:}
      connection-timeout: 10s
      socket-timeout: 60s
      ssl:
        certificate-authorities: ${ES_CERT_PATH:}
        verification-mode: ${ES_SSL_VERIFICATION_MODE:full}

server:
  port: 8080

logging:
  level:
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: INFO

