spring:
  application:
    name: spring-elastic
  data:
    elasticsearch:
      uris: ${ES_URIS:https://localhost:9200}
      username: ${ES_USERNAME:elastic}
      password: ${ES_PASSWORD:}
      connection-timeout: 10s
      socket-timeout: 60s

server:
  port: 8080

logging:
  level:
    com.example.springelastic: DEBUG
    org.springframework.data.elasticsearch: DEBUG
    org.elasticsearch: INFO

